//! Regenerate with cargo run -p lxst-codec2 --example generate_fft_tables --locked --offline.
//! Preserve the native initialiser's floating-point operation order exactly.
fn complex(name: &str, phases: impl Iterator<Item = f32>, length: usize) {
    println!("pub(super) static {name}: [kiss_fft_cpx; {length}] = [");
    for phase in phases {
        println!(
            "    kiss_fft_cpx {{ r: f32::from_bits(0x{:08x}), i: f32::from_bits(0x{:08x}) }},",
            libm::cosf(phase).to_bits(),
            libm::sinf(phase).to_bits()
        );
    }
    println!("];\n");
}
fn main() {
    println!(
        "// Generated by examples/generate_fft_tables.rs with pinned libm 0.2.16.\n// Immutable native FFT coefficients; no approximation or host trigonometry.\nuse super::inner::kiss_fft_cpx;\n"
    );
    for n in [128, 256, 512] {
        for inverse in [false, true] {
            complex(
                &format!(
                    "COMPLEX_{n}_{}",
                    if inverse { "INVERSE" } else { "FORWARD" }
                ),
                (0..n).map(|i| {
                    let mut phase = -2.0 * core::f64::consts::PI * i as f64 / n as f64;
                    if inverse {
                        phase *= -1.0;
                    }
                    phase as f32
                }),
                n,
            );
        }
    }
    for n in [128, 256] {
        for inverse in [false, true] {
            complex(
                &format!("REAL_{n}_{}", if inverse { "INVERSE" } else { "FORWARD" }),
                (0..n / 2).map(|i| {
                    let mut phase = (-core::f64::consts::PI
                        * (f64::from((i + 1) as f32 / n as f32) + 0.5))
                        as f32;
                    if inverse {
                        phase *= -1.0;
                    }
                    phase
                }),
                n / 2,
            );
        }
    }
}
